apiVersion: v2
name: trivy-operator
description: A Helm chart for trivy-operator
type: application
version: 2.4.1
appVersion: "1.16.0"
kubeVersion: ">=1.19.x-0"
keywords:
  - Trivy
  - Admission Controller
  - Operator
  - Image Secutity
home: https://devopstales.github.io/trivy-operator/
icon: https://github.com/devopstales/helm-charts/raw/main/icons/trivy.png
sources:
  - https://github.com/devopstales/trivy-operator
  - https://github.com/devopstales/helm-charts
deprecated: false
